"""Unit tests for the SF-NorMuon optimizer (schedule-free spectral).

Tests cover:
- Rejects non-2D params (matrix-only, like Muon/NorMuon)
- Rejects a params/gradients dtype mismatch
- Rejects a non-positive eps
- Numerical parity with an independent numpy transcription of Odyssey's
  SF-NorMuon core over FOUR steps on a 4x3 weight (1e-6), threading the z/x/m
  state sequentially so the y/z/x sequences, the Newton-Schulz orthogonalization,
  and the per-row L2 normalization all evolve. The reference threads state, so
  ref_{n+1} == step(ref_n) by construction.
- Weight decay applies to the fast iterate z_t, NOT the query point y_t: with a
  ZERO gradient the polar update is a fixed direction, and z must shrink by
  exactly (1 - weight_decay) toward zero relative to the no-decay run — the
  documented critical failure mode if decay were applied to y_t instead.

All reference values are generated by RUNNING
parity_refs/sf_normuon_parity_reference.py (values pasted verbatim from its JSON
output, 12 decimal places).
"""

from odyssey.tensor.any_tensor import AnyTensor
from odyssey.tensor.tensor_creation import zeros, zeros_like
from odyssey.training.optimizers.sf_normuon import (
    sf_normuon_step,
    sf_normuon_step_simple,
)


def _abs_diff(a: Float64, b: Float64) -> Float64:
    var d = a - b
    if d < 0:
        d = -d
    return d


def _seed_ramp(
    mut t: AnyTensor, count: Int, scale: Float64, off: Float64
) raises:
    for i in range(count):
        t.store[DType.float64](i, Float64(i) * scale + off)


def _assert_close(
    t: AnyTensor, expected: List[Float64], tol: Float64, label: String
) raises:
    for i in range(len(expected)):
        if _abs_diff(t.load[DType.float64](i), expected[i]) > tol:
            raise Error(label + " mismatch at " + String(i))


# Fixture config (parity4): 4x3 weight, eta=0.05, beta=0.9, mu=0.95,
# lambda_wd=0.01, weight_power=0.0. Gradient field g(y) = 0.5*y + G_const,
# G_const[i] = 0.03*i - 0.2; params init = 0.1*i - 0.5 (== z_1 == x_1).
# The 4x3 weight has 12 elements.


def _make_params() raises -> AnyTensor:
    var W = zeros([4, 3], DType.float64)
    _seed_ramp(W, 12, 0.1, -0.5)
    return W


def _make_gconst() raises -> AnyTensor:
    var G = zeros([4, 3], DType.float64)
    _seed_ramp(G, 12, 0.03, -0.2)
    return G


def _grad_at(y: AnyTensor, gconst: AnyTensor) raises -> AnyTensor:
    # g(y) = 0.5*y + G_const, elementwise (matches the reference grad_fn).
    var g = zeros([4, 3], DType.float64)
    for i in range(12):
        g.store[DType.float64](
            i,
            0.5 * y.load[DType.float64](i) + gconst.load[DType.float64](i),
        )
    return g


def test_reject_non_2d() raises:
    """SF-NorMuon rejects 1D params (matrix-only)."""
    print("Running test_reject_non_2d...")
    var p = zeros([10], DType.float64)
    var g = zeros([10], DType.float64)
    var z = zeros_like(p)
    var x = zeros_like(p)
    var m = zeros_like(p)
    try:
        var (_, _, _, _) = sf_normuon_step(p, g, z, x, m, 1, 0.05)
        raise Error("Should have rejected 1D params")
    except _:
        print("  ok rejected 1D params")
    print("test_reject_non_2d PASSED")


def test_reject_dtype_mismatch() raises:
    """SF-NorMuon rejects a params/gradients dtype mismatch."""
    print("Running test_reject_dtype_mismatch...")
    var p = zeros([4, 3], DType.float32)
    var g = zeros([4, 3], DType.float16)
    var z = zeros([4, 3], DType.float32)
    var x = zeros([4, 3], DType.float32)
    var m = zeros([4, 3], DType.float32)
    try:
        var (_, _, _, _) = sf_normuon_step(p, g, z, x, m, 1, 0.05)
        raise Error("Should have rejected dtype mismatch")
    except _:
        print("  ok rejected dtype mismatch")
    print("test_reject_dtype_mismatch PASSED")


def test_reject_bad_eps() raises:
    """A non-positive eps must raise."""
    print("Running test_reject_bad_eps...")
    var p = _make_params()
    var g = zeros([4, 3], DType.float64)
    var z = zeros_like(p)
    var x = zeros_like(p)
    var m = zeros_like(p)
    try:
        var (_, _, _, _) = sf_normuon_step(p, g, z, x, m, 1, 0.05, eps=0.0)
        raise Error("Should have rejected eps=0")
    except _:
        print("  ok rejected eps=0")
    print("test_reject_bad_eps PASSED")


def test_parity_four_step() raises:
    """Match the numpy transcription over 4 steps (1e-6).

    Reference regenerated by RUNNING parity_refs/sf_normuon_parity_reference.py
    (section "parity4"); steps[n].z / .x / .momentum pasted verbatim. The step
    threads z/x/m sequentially, and the gradient is evaluated at the query point
    y_t returned by the previous call (init y_1 = params).
    """
    print("Running test_parity_four_step...")

    # parity4.steps[0] (t=1)
    var z1 = List[Float64]()
    z1.append(-0.450941731244)
    z1.append(-0.372534729128)
    z1.append(-0.294127727013)
    z1.append(-0.153704691415)
    z1.append(-0.086676514950)
    z1.append(-0.019648338485)
    z1.append(0.121029966412)
    z1.append(0.187228235403)
    z1.append(0.253426504393)
    z1.append(0.395884816293)
    z1.append(0.472593318232)
    z1.append(0.549301820171)
    var x1 = List[Float64]()
    x1.append(-0.475470865622)
    x1.append(-0.386267364564)
    x1.append(-0.297063863506)
    x1.append(-0.176852345707)
    x1.append(-0.093338257475)
    x1.append(-0.009824169242)
    x1.append(0.110514983206)
    x1.append(0.193614117701)
    x1.append(0.276713252197)
    x1.append(0.397942408146)
    x1.append(0.486296659116)
    x1.append(0.574650910085)
    var m1 = List[Float64]()
    m1.append(-0.022500000000)
    m1.append(-0.018500000000)
    m1.append(-0.014500000000)
    m1.append(-0.010500000000)
    m1.append(-0.006500000000)
    m1.append(-0.002500000000)
    m1.append(0.001500000000)
    m1.append(0.005500000000)
    m1.append(0.009500000000)
    m1.append(0.013500000000)
    m1.append(0.017500000000)
    m1.append(0.021500000000)

    # parity4.steps[3] (t=4) — final z/x
    var z4 = List[Float64]()
    z4.append(-0.307280628208)
    z4.append(-0.290988799951)
    z4.append(-0.274696971693)
    z4.append(-0.016723095327)
    z4.append(-0.045333831735)
    z4.append(-0.073944568143)
    z4.append(0.180069278297)
    z4.append(0.147826683956)
    z4.append(0.115584089615)
    z4.append(0.381554157399)
    z4.append(0.391129696434)
    z4.append(0.400705235470)
    var x4 = List[Float64]()
    x4.append(-0.403039450275)
    x4.append(-0.345375108682)
    x4.append(-0.287710767090)
    x4.append(-0.108058583333)
    x4.append(-0.072934845099)
    x4.append(-0.037811106864)
    x4.append(0.140763828638)
    x4.append(0.174129937452)
    x4.append(0.207496046266)
    x4.append(0.391171432284)
    x4.append(0.445464302558)
    x4.append(0.499757172832)

    var gconst = _make_gconst()
    var params = _make_params()
    var z = _make_params()  # z_1 = params
    var x = _make_params()  # x_1 = params
    var m = zeros_like(params)
    var y = _make_params()  # y_1 = params

    var z_new: AnyTensor
    var x_new: AnyTensor
    var m_new: AnyTensor
    var y_next: AnyTensor

    # Step 1
    var g = _grad_at(y, gconst)
    (z_new, x_new, m_new, y_next) = sf_normuon_step(
        params, g, z, x, m, 1, 0.05, 0.9, 0.95, 0.01, 0.0
    )
    _assert_close(z_new, z1, 1e-6, "SF-NorMuon step-1 z")
    _assert_close(x_new, x1, 1e-6, "SF-NorMuon step-1 x")
    _assert_close(m_new, m1, 1e-6, "SF-NorMuon step-1 momentum")
    z = z_new
    x = x_new
    m = m_new
    y = y_next

    # Steps 2..4
    for t in range(2, 5):
        g = _grad_at(y, gconst)
        (z_new, x_new, m_new, y_next) = sf_normuon_step(
            params, g, z, x, m, t, 0.05, 0.9, 0.95, 0.01, 0.0
        )
        z = z_new
        x = x_new
        m = m_new
        y = y_next

    _assert_close(z, z4, 1e-6, "SF-NorMuon step-4 z")
    _assert_close(x, x4, 1e-6, "SF-NorMuon step-4 x")

    print("  ok 4-step y/z/x + polar + row-norm matches the reference to 1e-6")
    print("test_parity_four_step PASSED")


def test_weight_decay_on_z_not_y() raises:
    """Weight decay shrinks the FAST iterate z_t, not the query point.

    With a ZERO gradient the momentum EMA stays 0, so the polar factor P is
    identical between a decay and a no-decay run (same Newton-Schulz on the same
    zero-momentum -> same row-normalized direction). Therefore the ONLY
    difference in z_2 is the (1 - lambda_wd) factor multiplying z_1 = params:
        z_decay   = (1 - wd)*params - lr*P
        z_nodecay =        params   - lr*P
    so  z_decay - z_nodecay = -wd*params, elementwise. This is the structural
    proof that decay hits z (not y): if decay were applied to y_t the query
    point would change P and this exact relation would NOT hold.
    """
    print("Running test_weight_decay_on_z_not_y...")

    var params = _make_params()
    var g = zeros([4, 3], DType.float64)  # zero gradient
    var z = _make_params()
    var x = _make_params()
    var m = zeros_like(params)
    var wd = 0.1
    var lr = 0.05

    var z_decay: AnyTensor
    var z_nodecay: AnyTensor
    var _x: AnyTensor
    var _m: AnyTensor
    var _y: AnyTensor
    (z_decay, _x, _m, _y) = sf_normuon_step(
        params, g, z, x, m, 1, lr, 0.9, 0.95, wd, 0.0
    )
    (z_nodecay, _x, _m, _y) = sf_normuon_step(
        params, g, z, x, m, 1, lr, 0.9, 0.95, 0.0, 0.0
    )

    for i in range(12):
        var expected = -wd * params.load[DType.float64](i)
        var actual = z_decay.load[DType.float64](i) - z_nodecay.load[
            DType.float64
        ](i)
        if _abs_diff(actual, expected) > 1e-9:
            raise Error(
                "weight decay must apply to z_t (=-wd*params); mismatch at "
                + String(i)
            )

    print("  ok weight decay applies to the fast iterate z_t, not y_t")
    print("test_weight_decay_on_z_not_y PASSED")


def test_simple_wrapper_runs() raises:
    """The _simple convenience wrapper produces a finite 4x3 step."""
    print("Running test_simple_wrapper_runs...")
    var params = _make_params()
    var g = _make_gconst()
    var z = _make_params()
    var x = _make_params()
    var m = zeros_like(params)
    var new_z: AnyTensor
    var _nx: AnyTensor
    var _nm: AnyTensor
    var _ny: AnyTensor
    (new_z, _nx, _nm, _ny) = sf_normuon_step_simple(params, g, z, x, m, 1, 0.05)
    if new_z.numel() != 12:
        raise Error("simple wrapper returned wrong shape")
    print("  ok simple wrapper produced a 4x3 step")
    print("test_simple_wrapper_runs PASSED")


def main() raises:
    """Run all SF-NorMuon tests."""
    print("=" * 60)
    print("SF-NorMuon Optimizer Test Suite")
    print("=" * 60)
    test_reject_non_2d()
    test_reject_dtype_mismatch()
    test_reject_bad_eps()
    test_parity_four_step()
    test_weight_decay_on_z_not_y()
    test_simple_wrapper_runs()
    print("=" * 60)
    print("All SF-NorMuon tests PASSED")
    print("=" * 60)
