"""Unit tests for the LionMuon optimizer (alternating Lion / Muon).

Tests cover:
- Rejects a non-positive period
- Numerical parity with an independent numpy transcription of Odyssey's Lion and
  Muon cores across a 3-step alternation (period=4: Muon, Lion, Lion), threading
  SEPARATE Lion / Muon momentum buffers — validates both branches and buffer
  pass-through continuity (1e-6)
- Steady-state behaviour across >2 full periods (period=3, 9 steps, constant
  gradient): the Lion steps' sign pattern and both momentum-buffer trajectories
  match the two-buffer reference — the buffer assertions are what a shared-buffer
  regression would break, since Muon's heavy-ball accumulator (~||g||/(1-beta))
  must never leak into Lion's gradient-EMA buffer (O(||g||))
- The schedule dispatches correctly (step 0 -> Muon, step 1 -> Lion) by checking
  the two produce different parameter updates for the same inputs

All reference values are generated by running
parity_refs/lionmuon_parity_reference.py (values pasted verbatim from its JSON
output, 12 decimal places); the script threads state sequentially, so
ref_{n+1} == rule(ref_n) by construction.
"""

from odyssey.tensor.any_tensor import AnyTensor, zeros, zeros_like
from odyssey.training.optimizers.lionmuon import (
    lionmuon_step,
    lionmuon_step_simple,
)


def _abs_diff(a: Float64, b: Float64) -> Float64:
    var d = a - b
    if d < 0:
        d = -d
    return d


def _seed_ramp(
    mut t: AnyTensor, count: Int, scale: Float64, off: Float64
) raises:
    for i in range(count):
        t.store[DType.float64](i, Float64(i) * scale + off)


def _assert_close(
    t: AnyTensor, expected: List[Float64], tol: Float64, label: String
) raises:
    for i in range(len(expected)):
        if _abs_diff(t.load[DType.float64](i), expected[i]) > tol:
            raise Error(label + " mismatch at " + String(i))


def test_reject_bad_period() raises:
    """A non-positive period must raise."""
    print("Running test_reject_bad_period...")
    var W = zeros([3, 4], DType.float64)
    var G = zeros([3, 4], DType.float64)
    var LM = zeros_like(W)
    var MM = zeros_like(W)
    try:
        var (_, _, _) = lionmuon_step(W, G, LM, MM, 0.1, 0, 0)
        raise Error("Should have rejected period = 0")
    except e:
        print("  ok rejected period = 0")
    print("test_reject_bad_period PASSED")


def test_parity_three_step() raises:
    """Match the numpy transcription over 3 steps (period=4) to 1e-6.

    Reference values regenerated by RUNNING
    parity_refs/lionmuon_parity_reference.py (section "parity3") and pasting
    steps[n].params verbatim. Step 0 runs Muon (writes only the Muon buffer),
    steps 1-2 run Lion (write only the Lion buffer); the inactive buffer passes
    through unchanged each step.
    """
    print("Running test_parity_three_step...")

    # parity3.steps[0].params — after step 0 (Muon).
    var ref0 = List[Float64]()
    ref0.append(-0.485037439477)
    ref0.append(-0.390636308696)
    ref0.append(-0.296235177915)
    ref0.append(-0.201834047135)
    ref0.append(-0.089532875475)
    ref0.append(0.003772334436)
    ref0.append(0.097077544346)
    ref0.append(0.190382754257)
    ref0.append(0.305971688527)
    ref0.append(0.398180977568)
    ref0.append(0.490390266608)
    ref0.append(0.582599555648)

    # parity3.steps[1].params — after step 1 (Lion).
    var ref1 = List[Float64]()
    ref1.append(-0.385037439477)
    ref1.append(-0.290636308696)
    ref1.append(-0.196235177915)
    ref1.append(-0.101834047135)
    ref1.append(0.010467124525)
    ref1.append(0.103772334436)
    ref1.append(-0.002922455654)
    ref1.append(0.090382754257)
    ref1.append(0.205971688527)
    ref1.append(0.298180977568)
    ref1.append(0.390390266608)
    ref1.append(0.482599555648)

    # parity3.steps[2].params — after step 2 (Lion).
    var ref2 = List[Float64]()
    ref2.append(-0.285037439477)
    ref2.append(-0.190636308696)
    ref2.append(-0.096235177915)
    ref2.append(-0.001834047135)
    ref2.append(0.110467124525)
    ref2.append(0.203772334436)
    ref2.append(-0.102922455654)
    ref2.append(-0.009617245743)
    ref2.append(0.105971688527)
    ref2.append(0.198180977568)
    ref2.append(0.290390266608)
    ref2.append(0.382599555648)

    var W = zeros([3, 4], DType.float64)
    _seed_ramp(W, 12, 0.1, -0.5)
    var G = zeros([3, 4], DType.float64)
    _seed_ramp(G, 12, 0.05, -0.3)
    var LM = zeros_like(W)
    var MM = zeros_like(W)

    # Step 0 (Muon) — writes the Muon buffer; the Lion buffer must stay zero.
    var (p0, lm0, mm0) = lionmuon_step(W, G, LM, MM, 0.1, 0, 4)
    _assert_close(p0, ref0, 1e-6, "LionMuon step-0 (Muon) params")
    for i in range(12):
        if _abs_diff(lm0.load[DType.float64](i), 0.0) > 1e-12:
            raise Error("Muon step must not touch the Lion buffer")
    W = p0
    LM = lm0
    MM = mm0

    # Step 1 (Lion) — writes the Lion buffer; the Muon buffer passes through.
    var (p1, lm1, mm1) = lionmuon_step(W, G, LM, MM, 0.1, 1, 4)
    _assert_close(p1, ref1, 1e-6, "LionMuon step-1 (Lion) params")
    for i in range(12):
        if (
            _abs_diff(mm1.load[DType.float64](i), MM.load[DType.float64](i))
            > 1e-12
        ):
            raise Error("Lion step must not touch the Muon buffer")
    W = p1
    LM = lm1
    MM = mm1

    # Step 2 (Lion) — the Lion EMA continues from its own buffer.
    var (p2, _, _) = lionmuon_step(W, G, LM, MM, 0.1, 2, 4)
    _assert_close(p2, ref2, 1e-6, "LionMuon step-2 (Lion) params")

    print("  ok Muon (step 0) and Lion (steps 1-2) match the reference to 1e-6")
    print("test_parity_three_step PASSED")


def test_steady_state_two_periods() raises:
    """Run >2 full periods (period=3, 9 steps, constant gradient).

    Asserts against parity_refs/lionmuon_parity_reference.py section "steady9":
    - every Lion step moves every element by exactly +/- lr with the reference
      sign pattern (steady9.steps[*].lion_update_signs — constant across all six
      Lion steps for this fixture: -1 for the six negative-gradient elements,
      +1 for the six positive ones);
    - after step 3 and step 8 the Lion and Muon buffers match the reference to
      1e-6. By step 8 the Muon heavy-ball buffer has accumulated to ~3.4x ||g||
      elementwise (0.8558 vs 0.25 max) while the Lion EMA buffer stays at
      ~0.07x ||g|| (0.0176 max) — under the old shared-buffer design a single
      buffer cannot satisfy both trajectories, so these assertions are the
      regression guard against re-merging the buffers;
    - final params (after step 8) match the reference to 1e-6.
    """
    print("Running test_steady_state_two_periods...")

    # steady9.steps[3].lion_momentum — untouched by the step-3 Muon update.
    var s3_lion_m = List[Float64]()
    s3_lion_m.append(-0.005970000000)
    s3_lion_m.append(-0.004975000000)
    s3_lion_m.append(-0.003980000000)
    s3_lion_m.append(-0.002985000000)
    s3_lion_m.append(-0.001990000000)
    s3_lion_m.append(-0.000995000000)
    s3_lion_m.append(0.000000000000)
    s3_lion_m.append(0.000995000000)
    s3_lion_m.append(0.001990000000)
    s3_lion_m.append(0.002985000000)
    s3_lion_m.append(0.003980000000)
    s3_lion_m.append(0.004975000000)

    # steady9.steps[3].muon_momentum — second heavy-ball accumulation.
    var s3_muon_m = List[Float64]()
    s3_muon_m.append(-0.585000000000)
    s3_muon_m.append(-0.487500000000)
    s3_muon_m.append(-0.390000000000)
    s3_muon_m.append(-0.292500000000)
    s3_muon_m.append(-0.195000000000)
    s3_muon_m.append(-0.097500000000)
    s3_muon_m.append(0.000000000000)
    s3_muon_m.append(0.097500000000)
    s3_muon_m.append(0.195000000000)
    s3_muon_m.append(0.292500000000)
    s3_muon_m.append(0.390000000000)
    s3_muon_m.append(0.487500000000)

    # steady9.steps[8].params.
    var s8_params = List[Float64]()
    s8_params.append(0.144887681704)
    s8_params.append(0.228091073992)
    s8_params.append(0.311294466280)
    s8_params.append(0.394497858568)
    s8_params.append(0.531401373676)
    s8_params.append(0.611317003343)
    s8_params.append(-0.508767366991)
    s8_params.append(-0.428851737325)
    s8_params.append(-0.282084934351)
    s8_params.append(-0.205457067307)
    s8_params.append(-0.128829200262)
    s8_params.append(-0.052201333218)

    # steady9.steps[8].lion_momentum — stays at gradient-EMA scale.
    var s8_lion_m = List[Float64]()
    s8_lion_m.append(-0.017555955180)
    s8_lion_m.append(-0.014629962650)
    s8_lion_m.append(-0.011703970120)
    s8_lion_m.append(-0.008777977590)
    s8_lion_m.append(-0.005851985060)
    s8_lion_m.append(-0.002925992530)
    s8_lion_m.append(0.000000000000)
    s8_lion_m.append(0.002925992530)
    s8_lion_m.append(0.005851985060)
    s8_lion_m.append(0.008777977590)
    s8_lion_m.append(0.011703970120)
    s8_lion_m.append(0.014629962650)

    # steady9.steps[8].muon_momentum — heavy-ball accumulator, ~3.4x ||g||.
    var s8_muon_m = List[Float64]()
    s8_muon_m.append(-0.855750000000)
    s8_muon_m.append(-0.713125000000)
    s8_muon_m.append(-0.570500000000)
    s8_muon_m.append(-0.427875000000)
    s8_muon_m.append(-0.285250000000)
    s8_muon_m.append(-0.142625000000)
    s8_muon_m.append(0.000000000000)
    s8_muon_m.append(0.142625000000)
    s8_muon_m.append(0.285250000000)
    s8_muon_m.append(0.427875000000)
    s8_muon_m.append(0.570500000000)
    s8_muon_m.append(0.713125000000)

    # steady9 Lion sign pattern (identical for all six Lion steps).
    var lion_signs = List[Float64]()
    for i in range(12):
        if i < 6:
            lion_signs.append(-1.0)
        else:
            lion_signs.append(1.0)

    var W = zeros([3, 4], DType.float64)
    _seed_ramp(W, 12, 0.1, -0.5)
    var G = zeros([3, 4], DType.float64)
    _seed_ramp(G, 12, 0.05, -0.3)
    var LM = zeros_like(W)
    var MM = zeros_like(W)
    var lr = 0.1

    for s in range(9):
        var W_prev = W
        var (p, lm, mm) = lionmuon_step(W, G, LM, MM, lr, s, 3)
        if s % 3 != 0:
            # Lion step: every element moves by exactly +/- lr; the realized
            # sign must match the reference pattern.
            for i in range(12):
                var moved = W_prev.load[DType.float64](i) - p.load[
                    DType.float64
                ](i)
                if _abs_diff(moved, lion_signs[i] * lr) > 1e-9:
                    raise Error(
                        "Lion sign pattern mismatch at step "
                        + String(s)
                        + " elem "
                        + String(i)
                    )
        W = p
        LM = lm
        MM = mm
        if s == 3:
            _assert_close(LM, s3_lion_m, 1e-6, "steady step-3 lion_momentum")
            _assert_close(MM, s3_muon_m, 1e-6, "steady step-3 muon_momentum")

    _assert_close(W, s8_params, 1e-6, "steady step-8 params")
    _assert_close(LM, s8_lion_m, 1e-6, "steady step-8 lion_momentum")
    _assert_close(MM, s8_muon_m, 1e-6, "steady step-8 muon_momentum")

    print("  ok 9-step steady state matches the two-buffer reference to 1e-6")
    print("test_steady_state_two_periods PASSED")


def test_branches_differ() raises:
    """Muon (step 0) and Lion (step 1) must produce different updates."""
    print("Running test_branches_differ...")
    var W = zeros([3, 4], DType.float64)
    _seed_ramp(W, 12, 0.1, -0.5)
    var G = zeros([3, 4], DType.float64)
    _seed_ramp(G, 12, 0.05, -0.3)
    var LM = zeros_like(W)
    var MM = zeros_like(W)

    var (p_muon, _, _) = lionmuon_step(W, G, LM, MM, 0.1, 0, 4)  # Muon
    var (p_lion, _, _) = lionmuon_step(W, G, LM, MM, 0.1, 1, 4)  # Lion
    var any_diff = False
    for i in range(12):
        if (
            _abs_diff(
                p_muon.load[DType.float64](i), p_lion.load[DType.float64](i)
            )
            > 1e-9
        ):
            any_diff = True
    if not any_diff:
        raise Error("Muon and Lion branches produced identical updates")
    print("  ok the two branches differ")
    print("test_branches_differ PASSED")


def test_simple_wrapper_runs() raises:
    """The _simple convenience wrapper produces a finite step."""
    print("Running test_simple_wrapper_runs...")
    var W = zeros([3, 4], DType.float64)
    _seed_ramp(W, 12, 0.1, -0.5)
    var G = zeros([3, 4], DType.float64)
    _seed_ramp(G, 12, 0.05, -0.3)
    var LM = zeros_like(W)
    var MM = zeros_like(W)
    var (new_p, _, _) = lionmuon_step_simple(W, G, LM, MM, 0.1, 0)
    if new_p.numel() != 12:
        raise Error("simple wrapper returned wrong shape")
    print("  ok simple wrapper produced a 3x4 step")
    print("test_simple_wrapper_runs PASSED")


def main() raises:
    """Run all LionMuon tests."""
    print("=" * 60)
    print("LionMuon Optimizer Test Suite")
    print("=" * 60)
    test_reject_bad_period()
    test_parity_three_step()
    test_steady_state_two_periods()
    test_branches_differ()
    test_simple_wrapper_runs()
    print("=" * 60)
    print("All LionMuon tests PASSED")
    print("=" * 60)
