#!/usr/bin/env python3
"""Safely publish deterministic dependency artifacts from Dependabot CI.

The ``package`` command runs in a read-only pull-request workflow and emits
untrusted data. The ``publish`` command runs only from the default branch,
validates the artifact and live pull request, creates a GitHub-signed exact
child commit, and dispatches a literal allowlist of read-only checks.

Python is used because this automation needs authenticated HTTPS, JSON,
base64, hashing, and explicit error handling (ADR-001). It uses only the
standard library.
"""

from __future__ import annotations

import argparse
import base64
import binascii
import copy
import hashlib
import io
import json
import os
import re
import stat

# Fixed trusted command vectors are executed with shell=False.
import subprocess  # nosec B404
import sys
import tempfile
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from collections.abc import Callable, Mapping, Sequence
from http.client import HTTPMessage
from pathlib import Path
from typing import Any, NamedTuple

ARTIFACT_NAME = "dependabot-generated-dependencies"
ARTIFACT_PRODUCER = "dependabot-uv-lock"
ARTIFACT_SCHEMA = 1
SNAPSHOT_SCHEMA = 1
GENERATOR_WORKFLOW = "Regenerate dependency files on Dependabot PRs"
GENERATOR_WORKFLOW_PATH = ".github/workflows/dependabot-uv-lock.yml"
GENERATED_PATHS = ("uv.lock", "requirements.txt", "requirements-dev.txt")
MANIFEST_NAME = "manifest.json"
REQUIRED_WORKFLOWS = (
    "_required.yml",
    "comprehensive-tests.yml",
    "pre-commit.yml",
    "workflow-smoke-test.yml",
)
REQUIRED_WORKFLOW_PATHS = tuple(f".github/workflows/{workflow}" for workflow in REQUIRED_WORKFLOWS)
PROJECT_METADATA_PATH = "pyproject.toml"
PYTHON_VERSION_PATH = ".python-version"
REPOSITORY_DATA_PATHS = (
    *GENERATED_PATHS,
    PROJECT_METADATA_PATH,
    PYTHON_VERSION_PATH,
    *REQUIRED_WORKFLOW_PATHS,
)
BOT_LOGIN = "dependabot[bot]"
DCO_BODY = "Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
GRAPHQL_URL = "https://api.github.com/graphql"
MAX_GENERATED_FILE_BYTES = 16 * 1024 * 1024
MAX_MANIFEST_BYTES = 64 * 1024
MAX_ARTIFACT_ARCHIVE_BYTES = 64 * 1024 * 1024
MAX_REPOSITORY_DATA_BYTES = 16 * 1024 * 1024
TRUSTED_UV_VERSION = "0.12.0"
TRUSTED_REGISTRIES = frozenset({"https://pypi.org/simple"})
TRUSTED_DISTRIBUTION_HOSTS = frozenset({"files.pythonhosted.org"})
OID_PATTERN = re.compile(r"^[0-9a-f]{40}(?:[0-9a-f]{24})?$")
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
REPOSITORY_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
DEPENDENCY_NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")
DEPENDENCY_SPECIFIER_PATTERN = re.compile(r"^[A-Za-z0-9*+!._<>=~, -]*$")

CREATE_COMMIT_MUTATION = """
mutation CommitGeneratedDependencies($input: CreateCommitOnBranchInput!) {
  createCommitOnBranch(input: $input) {
    commit {
      oid
      url
      signature {
        isValid
        state
        wasSignedByGitHub
      }
    }
    ref {
      name
      target {
        oid
      }
    }
  }
}
""".strip()

VERIFY_COMMIT_QUERY = """
query VerifyGeneratedCommit($owner: String!, $name: String!, $oid: GitObjectID!) {
  repository(owner: $owner, name: $name) {
    object(oid: $oid) {
      ... on Commit {
        oid
        url
        signature {
          isValid
          state
          wasSignedByGitHub
        }
      }
    }
  }
}
""".strip()


class PublishError(RuntimeError):
    """Raised when the trusted publication contract is not satisfied."""


class StaleBranch(RuntimeError):
    """Signals a safe no-op because the Dependabot branch moved or disappeared."""


class ExactChildMismatch(PublishError):
    """Raised when a moved branch is not the exact trusted generated child."""


class _NoRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Expose GitHub's signed artifact redirect without forwarding the token."""

    def redirect_request(
        self,
        request: urllib.request.Request,
        file_pointer: Any,
        code: int,
        message: str,
        headers: HTTPMessage,
        new_url: str,
    ) -> None:
        del request, file_pointer, code, message, headers, new_url
        return None


class RunContext(NamedTuple):
    """Trusted metadata from the workflow_run webhook."""

    repository: str
    default_branch: str
    head_ref: str
    head_sha: str
    run_id: int
    run_attempt: int
    workflow_id: int
    repository_id: int
    head_repository_id: int


class ArtifactBundle(NamedTuple):
    """Validated generated bytes plus their bound source metadata."""

    repository: str
    pr_number: int
    head_ref: str
    head_sha: str
    changed: bool
    files: dict[str, bytes]


class ArtifactMetadata(NamedTuple):
    """Authenticated archive metadata returned by GitHub."""

    artifact_id: int
    size_in_bytes: int
    digest: str


class CommitResult(NamedTuple):
    """Verified GitHub-signed exact child commit."""

    oid: str
    url: str


class PublishResult(NamedTuple):
    """Publication status for CLI logging and unit tests."""

    status: str
    oid: str | None
    dispatched: int


GraphQLPayload = dict[str, Any]
GraphQLSender = Callable[[GraphQLPayload, str], GraphQLPayload]
UrlOpener = Callable[..., Any]


def _mapping(value: object, description: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise PublishError(f"missing or malformed {description}")
    return value


def _integer(value: object, description: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise PublishError(f"{description} must be a positive integer")
    return value


def _string(value: object, description: str) -> str:
    if not isinstance(value, str) or not value:
        raise PublishError(f"{description} must be a non-empty string")
    return value


def _validate_repository(repository: str) -> None:
    if not REPOSITORY_PATTERN.fullmatch(repository):
        raise PublishError(f"invalid repository: {repository!r}")


def _validate_branch(branch: str) -> None:
    invalid_character = any(character.isspace() or ord(character) < 32 for character in branch)
    if (
        not branch
        or branch.startswith(("refs/", "/"))
        or branch.endswith(("/", "."))
        or ".." in branch
        or "@{" in branch
        or "//" in branch
        or invalid_character
        or any(character in branch for character in r"~^:?*[\ ")
    ):
        raise PublishError(f"invalid unqualified branch name: {branch!r}")


def _validate_oid(oid: str, description: str = "object ID") -> None:
    if not OID_PATTERN.fullmatch(oid):
        raise PublishError(f"{description} must be a lowercase 40- or 64-character hexadecimal object ID")


def _read_regular_file(path: Path, *, maximum_bytes: int, description: str) -> bytes:
    try:
        file_stat = path.lstat()
    except OSError as error:
        raise PublishError(f"unable to stat {description}: {error}") from error
    if stat.S_ISLNK(file_stat.st_mode) or not stat.S_ISREG(file_stat.st_mode):
        raise PublishError(f"{description} must be a regular non-symlink file")
    if file_stat.st_size > maximum_bytes:
        raise PublishError(f"{description} exceeds the {maximum_bytes}-byte limit")
    try:
        return path.read_bytes()
    except OSError as error:
        raise PublishError(f"unable to read {description}: {error}") from error


def _read_generated_files(repo_root: Path) -> dict[str, bytes]:
    return {
        relative_path: _read_regular_file(
            repo_root / relative_path,
            maximum_bytes=MAX_GENERATED_FILE_BYTES,
            description=f"generated file {relative_path}",
        )
        for relative_path in GENERATED_PATHS
    }


def _snapshot_document(contents: Mapping[str, bytes]) -> dict[str, object]:
    return {
        "schema_version": SNAPSHOT_SCHEMA,
        "files": [
            {
                "path": relative_path,
                "sha256": hashlib.sha256(contents[relative_path]).hexdigest(),
                "size": len(contents[relative_path]),
            }
            for relative_path in GENERATED_PATHS
        ],
    }


def write_dependency_snapshot(repo_root: Path, snapshot_path: Path) -> None:
    """Hash the final verified generated files into one exact snapshot."""
    if snapshot_path.exists() or snapshot_path.is_symlink():
        raise PublishError(f"dependency snapshot already exists: {snapshot_path}")
    contents = _read_generated_files(repo_root)
    snapshot_text = json.dumps(_snapshot_document(contents), indent=2, sort_keys=True) + "\n"
    if len(snapshot_text.encode()) > MAX_MANIFEST_BYTES:
        raise PublishError("dependency snapshot exceeds the trusted size limit")
    try:
        snapshot_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot_path.write_text(snapshot_text, encoding="utf-8")
    except OSError as error:
        raise PublishError(f"unable to write dependency snapshot: {error}") from error


def _load_dependency_snapshot(snapshot_path: Path) -> dict[str, tuple[str, int]]:
    raw_snapshot = _read_regular_file(
        snapshot_path,
        maximum_bytes=MAX_MANIFEST_BYTES,
        description="verified dependency snapshot",
    )
    try:
        snapshot = json.loads(raw_snapshot)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PublishError("verified dependency snapshot is not valid JSON") from error
    snapshot_map = _mapping(snapshot, "verified dependency snapshot")
    if set(snapshot_map) != {"schema_version", "files"} or snapshot_map.get("schema_version") != SNAPSHOT_SCHEMA:
        raise PublishError("verified dependency snapshot has an invalid schema")
    raw_files = snapshot_map.get("files")
    if not isinstance(raw_files, list) or len(raw_files) != len(GENERATED_PATHS):
        raise PublishError("verified dependency snapshot must describe exactly three files")
    described: dict[str, tuple[str, int]] = {}
    for raw_entry in raw_files:
        entry = _mapping(raw_entry, "verified dependency snapshot file")
        if set(entry) != {"path", "sha256", "size"}:
            raise PublishError("verified dependency snapshot file has unexpected fields")
        relative_path = _string(entry.get("path"), "verified dependency snapshot path")
        digest = entry.get("sha256")
        size = entry.get("size")
        if relative_path not in GENERATED_PATHS or relative_path in described:
            raise PublishError("verified dependency snapshot has a duplicate or unexpected path")
        if not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
            raise PublishError("verified dependency snapshot has an invalid digest")
        if isinstance(size, bool) or not isinstance(size, int) or size < 0:
            raise PublishError("verified dependency snapshot has an invalid size")
        described[relative_path] = (digest, size)
    if set(described) != set(GENERATED_PATHS):
        raise PublishError("verified dependency snapshot does not describe the exact generated file set")
    return described


def package_artifact(
    *,
    repo_root: Path,
    artifact_root: Path,
    repository: str,
    pr_number: int,
    head_repository: str,
    head_ref: str,
    head_sha: str,
    run_id: int,
    run_attempt: int,
    producer_status: str,
    changed: bool,
    snapshot_path: Path,
) -> None:
    """Create the exact four-file producer artifact."""
    _validate_repository(repository)
    if head_repository != repository:
        raise PublishError("Dependabot head repository must equal the target repository")
    _validate_branch(head_ref)
    _validate_oid(head_sha, "source head")
    _integer(pr_number, "pull request number")
    _integer(run_id, "workflow run ID")
    _integer(run_attempt, "workflow run attempt")
    if producer_status not in {"success", "failure", "cancelled"}:
        raise PublishError(f"invalid producer status: {producer_status!r}")
    if artifact_root.exists():
        raise PublishError(f"artifact root already exists: {artifact_root}")

    contents = _read_generated_files(repo_root)
    snapshot = _load_dependency_snapshot(snapshot_path)
    for relative_path in GENERATED_PATHS:
        digest, size = snapshot[relative_path]
        content = contents[relative_path]
        if hashlib.sha256(content).hexdigest() != digest or len(content) != size:
            raise PublishError(f"generated file changed after verified snapshot: {relative_path}")

    file_entries: list[dict[str, object]] = []
    for relative_path in GENERATED_PATHS:
        content = contents[relative_path]
        file_entries.append(
            {
                "path": relative_path,
                "sha256": hashlib.sha256(content).hexdigest(),
                "size": len(content),
            }
        )

    manifest = {
        "schema_version": ARTIFACT_SCHEMA,
        "producer": ARTIFACT_PRODUCER,
        "repository": repository,
        "pr_number": pr_number,
        "head_repository": head_repository,
        "head_ref": head_ref,
        "head_sha": head_sha,
        "workflow_run_id": run_id,
        "workflow_run_attempt": run_attempt,
        "producer_status": producer_status,
        "changed": changed,
        "files": file_entries,
    }
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    if _read_generated_files(repo_root) != contents:
        raise PublishError("generated files changed while packaging the verified snapshot")
    artifact_root.mkdir(parents=True)
    for relative_path in GENERATED_PATHS:
        (artifact_root / relative_path).write_bytes(contents[relative_path])
    (artifact_root / MANIFEST_NAME).write_text(manifest_text, encoding="utf-8")
    if _read_generated_files(repo_root) != contents:
        raise PublishError("generated files changed while packaging the verified snapshot")


def load_run_context(event_path: Path, *, target_repository: str) -> RunContext:
    """Validate the workflow_run event independently of artifact claims."""
    _validate_repository(target_repository)
    event_bytes = _read_regular_file(
        event_path,
        maximum_bytes=MAX_MANIFEST_BYTES * 8,
        description="workflow event",
    )
    try:
        event = json.loads(event_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PublishError("workflow event is not valid JSON") from error
    event_map = _mapping(event, "workflow event")
    repository = _mapping(event_map.get("repository"), "workflow event repository")
    if repository.get("full_name") != target_repository:
        raise PublishError("workflow event repository does not match TARGET_REPOSITORY")
    default_branch = _string(repository.get("default_branch"), "default branch")
    _validate_branch(default_branch)

    workflow_run = _mapping(event_map.get("workflow_run"), "workflow_run")
    if workflow_run.get("name") != GENERATOR_WORKFLOW:
        raise PublishError("workflow_run came from an unexpected workflow")
    if workflow_run.get("path") != GENERATOR_WORKFLOW_PATH:
        raise PublishError("workflow_run came from an unexpected workflow path")
    if workflow_run.get("event") != "pull_request" or workflow_run.get("conclusion") != "success":
        raise PublishError("workflow_run must be a successful pull_request run")
    actor = _mapping(workflow_run.get("actor"), "workflow_run actor")
    if actor.get("login") != BOT_LOGIN:
        raise PublishError("workflow_run actor is not Dependabot")
    head_repository = _mapping(workflow_run.get("head_repository"), "workflow_run head repository")
    if head_repository.get("full_name") != target_repository:
        raise PublishError("workflow_run head repository is not the target repository")
    run_repository = _mapping(workflow_run.get("repository"), "workflow_run repository")
    if run_repository.get("full_name") != target_repository:
        raise PublishError("workflow_run repository is not the target repository")

    head_ref = _string(workflow_run.get("head_branch"), "workflow_run head branch")
    head_sha = _string(workflow_run.get("head_sha"), "workflow_run head SHA")
    _validate_branch(head_ref)
    _validate_oid(head_sha, "workflow_run head SHA")
    return RunContext(
        repository=target_repository,
        default_branch=default_branch,
        head_ref=head_ref,
        head_sha=head_sha,
        run_id=_integer(workflow_run.get("id"), "workflow run ID"),
        run_attempt=_integer(workflow_run.get("run_attempt"), "workflow run attempt"),
        workflow_id=_integer(workflow_run.get("workflow_id"), "workflow ID"),
        repository_id=_integer(repository.get("id"), "repository ID"),
        head_repository_id=_integer(head_repository.get("id"), "head repository ID"),
    )


def validate_artifact_listing(
    response: Mapping[str, Any],
    *,
    context: RunContext,
) -> ArtifactMetadata:
    """Authenticate one bounded, non-expired artifact before downloading it."""
    total_count = response.get("total_count")
    raw_artifacts = response.get("artifacts")
    if total_count != 1 or not isinstance(raw_artifacts, list) or len(raw_artifacts) != 1:
        raise PublishError("source workflow run must publish exactly one dependency artifact")
    artifact = _mapping(raw_artifacts[0], "dependency artifact metadata")
    if artifact.get("name") != ARTIFACT_NAME:
        raise PublishError("dependency artifact has an unexpected name")
    if artifact.get("expired") is not False:
        raise PublishError("dependency artifact is expired or has no expiry state")
    artifact_id = _integer(artifact.get("id"), "dependency artifact ID")
    size_in_bytes = _integer(artifact.get("size_in_bytes"), "dependency artifact archive size")
    if size_in_bytes > MAX_ARTIFACT_ARCHIVE_BYTES:
        raise PublishError("dependency artifact archive size exceeds the trusted limit")
    raw_digest = artifact.get("digest")
    if not isinstance(raw_digest, str) or not raw_digest.startswith("sha256:"):
        raise PublishError("dependency artifact digest is missing or malformed")
    digest = raw_digest.removeprefix("sha256:")
    if not SHA256_PATTERN.fullmatch(digest):
        raise PublishError("dependency artifact digest is missing or malformed")

    source = _mapping(artifact.get("workflow_run"), "dependency artifact source workflow run")
    expected_source = {
        "id": context.run_id,
        "repository_id": context.repository_id,
        "head_repository_id": context.head_repository_id,
        "head_branch": context.head_ref,
        "head_sha": context.head_sha,
    }
    for field, expected in expected_source.items():
        if source.get(field) != expected:
            raise PublishError(f"dependency artifact source workflow run {field} does not match")
    return ArtifactMetadata(
        artifact_id=artifact_id,
        size_in_bytes=size_in_bytes,
        digest=digest,
    )


def read_safe_artifact_archive(archive: bytes) -> dict[str, bytes]:
    """Read the exact flat artifact in memory with no filesystem extraction."""
    if not archive or len(archive) > MAX_ARTIFACT_ARCHIVE_BYTES:
        raise PublishError("dependency artifact archive size exceeds the trusted limit")
    try:
        with zipfile.ZipFile(io.BytesIO(archive), mode="r") as bundle:
            entries = bundle.infolist()
            names = [entry.filename for entry in entries]
            if len(set(names)) != len(names):
                raise PublishError("dependency artifact archive contains a duplicate path")
            expected_names = {*GENERATED_PATHS, MANIFEST_NAME}
            if len(entries) != len(expected_names) or set(names) != expected_names:
                raise PublishError("dependency artifact archive must contain the exact flat file set")

            total_uncompressed = 0
            contents: dict[str, bytes] = {}
            for entry in entries:
                if entry.is_dir() or "/" in entry.filename or "\\" in entry.filename or entry.filename in {".", ".."}:
                    raise PublishError("dependency artifact archive must contain exact flat regular files")
                mode = entry.external_attr >> 16
                if mode and stat.S_ISLNK(mode):
                    raise PublishError("dependency artifact archive must not contain symlink entries")
                if entry.flag_bits & 0x1:
                    raise PublishError("dependency artifact archive must not contain encrypted entries")
                if entry.compress_type not in {zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED}:
                    raise PublishError("dependency artifact archive uses an unsupported compression method")
                maximum_bytes = MAX_MANIFEST_BYTES if entry.filename == MANIFEST_NAME else MAX_GENERATED_FILE_BYTES
                if entry.file_size > maximum_bytes:
                    raise PublishError(f"dependency artifact entry exceeds its size limit: {entry.filename}")
                total_uncompressed += entry.file_size
                if total_uncompressed > (MAX_MANIFEST_BYTES + len(GENERATED_PATHS) * MAX_GENERATED_FILE_BYTES):
                    raise PublishError("dependency artifact uncompressed size exceeds the trusted limit")
                with bundle.open(entry, mode="r") as source:
                    content = source.read(maximum_bytes + 1)
                    if len(content) > maximum_bytes or source.read(1):
                        raise PublishError(f"dependency artifact entry exceeds its size limit: {entry.filename}")
                if len(content) != entry.file_size:
                    raise PublishError(f"dependency artifact entry size is contradictory: {entry.filename}")
                contents[entry.filename] = content
    except (OSError, RuntimeError, zipfile.BadZipFile) as error:
        raise PublishError(f"dependency artifact is not a safe ZIP archive: {error}") from error
    return contents


def _artifact_redirect_url(
    metadata: ArtifactMetadata,
    context: RunContext,
    *,
    token: str,
    opener: UrlOpener | None = None,
) -> str:
    """Resolve GitHub's authenticated redirect without forwarding credentials."""
    if not token:
        raise PublishError("GITHUB_TOKEN is missing")
    request = urllib.request.Request(
        f"{_api_root(context.repository)}/actions/artifacts/{metadata.artifact_id}/zip",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "Odyssey-dependency-publisher",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="GET",
    )
    redirect_opener = opener
    if redirect_opener is None:
        redirect_opener = urllib.request.build_opener(_NoRedirectHandler()).open
    location: str | None = None
    try:
        with redirect_opener(request, timeout=30) as response:
            status_code = int(response.status)
            if status_code not in {302, 303, 307, 308}:
                raise PublishError(f"artifact download redirect returned HTTP {status_code}")
            location = response.headers.get("Location")
    except urllib.error.HTTPError as error:
        if error.code not in {302, 303, 307, 308}:
            raise PublishError(f"artifact download redirect failed with HTTP {error.code}") from error
        location = error.headers.get("Location")
        error.close()
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise PublishError(f"artifact download redirect failed: {error}") from error
    if not location:
        raise PublishError("artifact download redirect omitted its signed location")
    parsed = urllib.parse.urlsplit(location)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username is not None or parsed.password is not None:
        raise PublishError("artifact download redirect returned an unsafe location")
    return location


def download_artifact_archive(
    metadata: ArtifactMetadata,
    context: RunContext,
    *,
    token: str,
    redirect_opener: UrlOpener | None = None,
    download_opener: UrlOpener = urllib.request.urlopen,
) -> bytes:
    """Download one bounded archive by immutable artifact ID without auth forwarding."""
    signed_url = _artifact_redirect_url(
        metadata,
        context,
        token=token,
        opener=redirect_opener,
    )
    request = urllib.request.Request(
        signed_url,
        headers={"Accept": "application/zip", "User-Agent": "Odyssey-dependency-publisher"},
        method="GET",
    )
    try:
        with download_opener(request, timeout=30) as response:
            status_code = int(response.status)
            if status_code != 200:
                raise PublishError(f"artifact archive download failed with HTTP {status_code}")
            content_length = response.headers.get("Content-Length")
            if content_length is not None:
                try:
                    declared_length = int(content_length)
                except ValueError as error:
                    raise PublishError("artifact archive download returned an invalid length") from error
                if declared_length <= 0:
                    raise PublishError("artifact archive download returned an invalid length")
                if declared_length > MAX_ARTIFACT_ARCHIVE_BYTES:
                    raise PublishError("artifact archive download exceeds the trusted size limit")
            archive = response.read(MAX_ARTIFACT_ARCHIVE_BYTES + 1)
    except urllib.error.HTTPError as error:
        raise PublishError(f"artifact archive download failed with HTTP {error.code}") from error
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise PublishError(f"artifact archive download failed: {error}") from error
    if not archive or len(archive) > MAX_ARTIFACT_ARCHIVE_BYTES:
        raise PublishError("artifact archive download exceeds the trusted size limit")
    return archive


def download_validated_artifact(
    context: RunContext,
    *,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> ArtifactBundle:
    """Preflight, download, and validate one untrusted artifact entirely in memory."""
    query = urllib.parse.urlencode({"name": ARTIFACT_NAME, "per_page": 100})
    listing = _rest_get(
        f"{_api_root(context.repository)}/actions/runs/{context.run_id}/artifacts?{query}",
        token=token,
        opener=opener,
        description="dependency artifact listing",
    )
    if listing is None:
        raise PublishError("dependency artifact listing unexpectedly returned no response")
    metadata = validate_artifact_listing(listing, context=context)
    archive = download_artifact_archive(metadata, context, token=token)
    if len(archive) != metadata.size_in_bytes:
        raise PublishError("dependency artifact archive size contradicts GitHub metadata")
    if hashlib.sha256(archive).hexdigest() != metadata.digest:
        raise PublishError("dependency artifact archive digest contradicts GitHub metadata")
    entries = read_safe_artifact_archive(archive)
    return validate_artifact_entries(entries, context=context)


def validate_artifact(artifact_root: Path, *, context: RunContext) -> ArtifactBundle:
    """Fail closed unless the artifact is exact, internally valid, and event-bound."""
    if artifact_root.is_symlink() or not artifact_root.is_dir():
        raise PublishError("artifact root must be a regular directory")
    expected_names = {*GENERATED_PATHS, MANIFEST_NAME}
    try:
        entries = list(artifact_root.iterdir())
    except OSError as error:
        raise PublishError(f"unable to list artifact root: {error}") from error
    actual_names = {entry.name for entry in entries}
    if len(entries) != len(expected_names) or actual_names != expected_names:
        raise PublishError(f"artifact must contain exactly {sorted(expected_names)}; found {sorted(actual_names)}")
    if any(entry.is_symlink() or not entry.is_file() for entry in entries):
        raise PublishError("artifact entries must all be regular non-symlink files")

    contents = {
        entry.name: _read_regular_file(
            entry,
            maximum_bytes=MAX_MANIFEST_BYTES if entry.name == MANIFEST_NAME else MAX_GENERATED_FILE_BYTES,
            description=f"artifact entry {entry.name}",
        )
        for entry in entries
    }
    return validate_artifact_entries(contents, context=context)


def validate_artifact_entries(
    contents: Mapping[str, bytes],
    *,
    context: RunContext,
) -> ArtifactBundle:
    """Validate exact in-memory artifact entries against the workflow event."""
    expected_names = {*GENERATED_PATHS, MANIFEST_NAME}
    if set(contents) != expected_names or len(contents) != len(expected_names):
        raise PublishError(f"artifact must contain exactly {sorted(expected_names)}")
    for name, content in contents.items():
        maximum_bytes = MAX_MANIFEST_BYTES if name == MANIFEST_NAME else MAX_GENERATED_FILE_BYTES
        if not isinstance(content, bytes) or len(content) > maximum_bytes:
            raise PublishError(f"artifact entry is malformed or exceeds its size limit: {name}")

    manifest_bytes = contents[MANIFEST_NAME]
    try:
        manifest = json.loads(manifest_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PublishError("artifact manifest is not valid JSON") from error
    manifest_map = _mapping(manifest, "artifact manifest")
    expected_keys = {
        "schema_version",
        "producer",
        "repository",
        "pr_number",
        "head_repository",
        "head_ref",
        "head_sha",
        "workflow_run_id",
        "workflow_run_attempt",
        "producer_status",
        "changed",
        "files",
    }
    if set(manifest_map) != expected_keys:
        raise PublishError("artifact manifest has missing or unexpected fields")
    expected_metadata = {
        "schema_version": ARTIFACT_SCHEMA,
        "producer": ARTIFACT_PRODUCER,
        "repository": context.repository,
        "head_repository": context.repository,
        "head_ref": context.head_ref,
        "head_sha": context.head_sha,
        "workflow_run_id": context.run_id,
        "workflow_run_attempt": context.run_attempt,
        "producer_status": "success",
    }
    for key, expected_value in expected_metadata.items():
        if manifest_map.get(key) != expected_value:
            raise PublishError(f"artifact manifest {key} does not match the workflow event")
    pr_number = _integer(manifest_map.get("pr_number"), "artifact pull request number")
    changed = manifest_map.get("changed")
    if not isinstance(changed, bool):
        raise PublishError("artifact manifest changed field must be boolean")

    raw_file_entries = manifest_map.get("files")
    if not isinstance(raw_file_entries, list) or len(raw_file_entries) != len(GENERATED_PATHS):
        raise PublishError("artifact manifest must describe exactly three generated files")
    described_paths: set[str] = set()
    files: dict[str, bytes] = {}
    for raw_entry in raw_file_entries:
        entry = _mapping(raw_entry, "artifact file entry")
        if set(entry) != {"path", "sha256", "size"}:
            raise PublishError("artifact file entry has missing or unexpected fields")
        relative_path = _string(entry.get("path"), "artifact file path")
        if relative_path not in GENERATED_PATHS or relative_path in described_paths:
            raise PublishError(f"artifact manifest has duplicate or unexpected path: {relative_path}")
        described_paths.add(relative_path)
        content = contents[relative_path]
        digest = entry.get("sha256")
        size = entry.get("size")
        if not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
            raise PublishError(f"artifact manifest has invalid SHA-256 for {relative_path}")
        if isinstance(size, bool) or not isinstance(size, int) or size < 0:
            raise PublishError(f"artifact manifest has invalid size for {relative_path}")
        if hashlib.sha256(content).hexdigest() != digest or len(content) != size:
            raise PublishError(f"artifact file contradicts its manifest: {relative_path}")
        files[relative_path] = content
    if described_paths != set(GENERATED_PATHS):
        raise PublishError("artifact manifest does not describe the exact generated file set")

    return ArtifactBundle(
        repository=context.repository,
        pr_number=pr_number,
        head_ref=context.head_ref,
        head_sha=context.head_sha,
        changed=changed,
        files=files,
    )


def _parse_toml_document(content: bytes, description: str) -> dict[str, Any]:
    try:
        document = tomllib.loads(content.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise PublishError(f"{description} is not valid UTF-8 TOML") from error
    if not isinstance(document, dict):
        raise PublishError(f"{description} is not a TOML document")
    return document


def _dependency_parts(requirement: object, description: str) -> tuple[str, str, str]:
    if not isinstance(requirement, str) or not requirement:
        raise PublishError(f"{description} must contain only dependency strings")
    if (
        requirement != requirement.strip()
        or "\n" in requirement
        or "\r" in requirement
        or "@" in requirement
        or "/" in requirement
        or "\\" in requirement
        or "://" in requirement
        or requirement.startswith("-")
    ):
        raise PublishError(f"{description} contains an unsafe dependency URL, path, or option")
    match = DEPENDENCY_NAME_PATTERN.match(requirement)
    if match is None:
        raise PublishError(f"{description} contains a malformed dependency")
    specifier = requirement[match.end() :]
    if not DEPENDENCY_SPECIFIER_PATTERN.fullmatch(specifier):
        raise PublishError(f"{description} contains an unsupported dependency specifier")
    raw_name = match.group(0)
    normalized_name = re.sub(r"[-_.]+", "-", raw_name).lower()
    normalized_specifier = re.sub(r"\s+", "", specifier)
    return raw_name, normalized_name, normalized_specifier


def _dependency_name(requirement: object, description: str) -> str:
    return _dependency_parts(requirement, description)[1]


def _dependency_lists(document: Mapping[str, Any], description: str) -> dict[tuple[str, ...], list[str]]:
    locations: dict[tuple[str, ...], list[str]] = {}
    build_system = _mapping(document.get("build-system"), f"{description} build-system")
    project = _mapping(document.get("project"), f"{description} project")
    dependency_groups = _mapping(document.get("dependency-groups"), f"{description} dependency-groups")
    raw_locations: dict[tuple[str, ...], object] = {
        ("build-system", "requires"): build_system.get("requires"),
        ("project", "dependencies"): project.get("dependencies"),
        **{
            ("dependency-groups", str(group)): dependencies
            for group, dependencies in dependency_groups.items()
            if isinstance(group, str)
        },
    }
    if len(raw_locations) != len(dependency_groups) + 2:
        raise PublishError(f"{description} dependency groups have malformed names")
    for location, raw_dependencies in raw_locations.items():
        if not isinstance(raw_dependencies, list):
            raise PublishError(f"{description} {'.'.join(location)} must be a dependency list")
        dependencies = list(raw_dependencies)
        for dependency in dependencies:
            _dependency_name(dependency, f"{description} {'.'.join(location)}")
        locations[location] = dependencies
    return locations


def _replace_nested(document: dict[str, Any], location: tuple[str, ...], value: object) -> None:
    target = document
    for key in location[:-1]:
        nested = target.get(key)
        if not isinstance(nested, dict):
            raise PublishError("project metadata changed outside dependency declarations")
        target = nested
    target[location[-1]] = value


def _validate_candidate_pyproject(candidate: bytes, trusted: bytes) -> None:
    candidate_document = _parse_toml_document(candidate, "candidate pyproject.toml")
    trusted_document = _parse_toml_document(trusted, "trusted pyproject.toml")
    candidate_dependencies = _dependency_lists(candidate_document, "candidate pyproject.toml")
    trusted_dependencies = _dependency_lists(trusted_document, "trusted pyproject.toml")
    if set(candidate_dependencies) != set(trusted_dependencies):
        raise PublishError("candidate pyproject.toml changed dependency group structure")

    normalized_candidate = copy.deepcopy(candidate_document)
    for location, trusted_values in trusted_dependencies.items():
        candidate_values = candidate_dependencies[location]
        candidate_names = [
            _dependency_name(value, f"candidate pyproject.toml {'.'.join(location)}") for value in candidate_values
        ]
        trusted_names = [
            _dependency_name(value, f"trusted pyproject.toml {'.'.join(location)}") for value in trusted_values
        ]
        if candidate_names != trusted_names:
            raise PublishError(
                f"candidate pyproject.toml may change versions but not dependency identities in {'.'.join(location)}"
            )
        candidate_raw_names = [
            _dependency_parts(value, f"candidate pyproject.toml {'.'.join(location)}")[0] for value in candidate_values
        ]
        trusted_raw_names = [
            _dependency_parts(value, f"trusted pyproject.toml {'.'.join(location)}")[0] for value in trusted_values
        ]
        if candidate_raw_names != trusted_raw_names:
            raise PublishError(
                f"candidate pyproject.toml may not rewrite dependency identity spelling in {'.'.join(location)}"
            )
        _replace_nested(normalized_candidate, location, trusted_values)
    if normalized_candidate != trusted_document:
        raise PublishError("candidate pyproject.toml changed fields outside dependency version declarations")


def _validate_distribution_record(record: Mapping[str, Any], description: str) -> None:
    raw_url = record.get("url")
    if not isinstance(raw_url, str):
        raise PublishError(f"{description} has a malformed distribution URL")
    parsed = urllib.parse.urlsplit(raw_url)
    if (
        parsed.scheme != "https"
        or parsed.hostname not in TRUSTED_DISTRIBUTION_HOSTS
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
    ):
        raise PublishError(f"{description} contains an untrusted distribution URL")
    digest = record.get("hash")
    size = record.get("size")
    if (
        not isinstance(digest, str)
        or not digest.startswith("sha256:")
        or not SHA256_PATTERN.fullmatch(digest.removeprefix("sha256:"))
        or isinstance(size, bool)
        or not isinstance(size, int)
        or size <= 0
    ):
        raise PublishError(f"{description} distribution URL is not bound to a SHA-256 digest and size")


def _validate_lock_urls(value: object, description: str = "uv.lock") -> None:
    if isinstance(value, Mapping):
        if "url" in value:
            _validate_distribution_record(value, description)
        for key, nested in value.items():
            _validate_lock_urls(nested, f"{description}.{key}")
    elif isinstance(value, list):
        for index, nested in enumerate(value):
            _validate_lock_urls(nested, f"{description}[{index}]")


def _dependency_entry_requests(raw_entries: object, description: str) -> dict[str, set[str]]:
    if raw_entries is None:
        return {}
    if not isinstance(raw_entries, list):
        raise PublishError(f"{description} must be a dependency list")
    requests: dict[str, set[str]] = {}
    for raw_entry in raw_entries:
        entry = _mapping(raw_entry, f"{description} entry")
        name = _string(entry.get("name"), f"{description} dependency name")
        normalized_name = re.sub(r"[-_.]+", "-", name).lower()
        raw_extras = entry.get("extra", [])
        if not isinstance(raw_extras, list) or not all(
            isinstance(extra, str) and extra and extra == extra.strip() for extra in raw_extras
        ):
            raise PublishError(f"{description} dependency extras are malformed")
        requests.setdefault(normalized_name, set()).update(raw_extras)
    return requests


def _merge_dependency_requests(target: dict[str, set[str]], source: Mapping[str, set[str]]) -> None:
    for name, extras in source.items():
        target.setdefault(name, set()).update(extras)


def _validate_lock_reachability(raw_packages: list[object]) -> None:
    packages: dict[str, list[Mapping[str, Any]]] = {}
    roots: list[str] = []
    for index, raw_package in enumerate(raw_packages):
        package = _mapping(raw_package, f"uv.lock package {index}")
        name = _string(package.get("name"), f"uv.lock package {index} name")
        normalized_name = re.sub(r"[-_.]+", "-", name).lower()
        packages.setdefault(normalized_name, []).append(package)
        if package.get("source") == {"editable": "."}:
            roots.append(normalized_name)
    if roots != ["odyssey"]:
        raise PublishError("uv.lock must contain exactly one trusted Odyssey root")

    requested_extras: dict[str, set[str]] = {"odyssey": set()}
    processed_extras: dict[str, set[str]] = {}
    pending = ["odyssey"]
    while pending:
        name = pending.pop()
        extras = requested_extras[name]
        if processed_extras.get(name) == extras:
            continue
        processed_extras[name] = set(extras)
        requests: dict[str, set[str]] = {}
        found_extras: set[str] = set()
        for package in packages.get(name, []):
            _merge_dependency_requests(
                requests,
                _dependency_entry_requests(
                    package.get("dependencies"),
                    f"uv.lock package {name} dependencies",
                ),
            )
            raw_dev_dependencies = package.get("dev-dependencies")
            if raw_dev_dependencies is not None:
                dev_dependencies = _mapping(
                    raw_dev_dependencies,
                    f"uv.lock package {name} dev-dependencies",
                )
                for group, raw_entries in dev_dependencies.items():
                    _merge_dependency_requests(
                        requests,
                        _dependency_entry_requests(
                            raw_entries,
                            f"uv.lock package {name} dev-dependencies.{group}",
                        ),
                    )
            raw_optional_dependencies = package.get("optional-dependencies")
            if raw_optional_dependencies is not None:
                optional_dependencies = _mapping(
                    raw_optional_dependencies,
                    f"uv.lock package {name} optional-dependencies",
                )
                for extra in extras:
                    if extra not in optional_dependencies:
                        continue
                    found_extras.add(extra)
                    _merge_dependency_requests(
                        requests,
                        _dependency_entry_requests(
                            optional_dependencies[extra],
                            f"uv.lock package {name} optional-dependencies.{extra}",
                        ),
                    )
        missing_extras = extras - found_extras
        if missing_extras:
            raise PublishError(f"uv.lock package {name} references missing extras: {', '.join(sorted(missing_extras))}")
        for dependency, dependency_extras in requests.items():
            if dependency not in packages:
                raise PublishError(f"uv.lock references missing dependency package {dependency}")
            previous_extras = requested_extras.setdefault(dependency, set())
            changed = not dependency_extras.issubset(previous_extras)
            previous_extras.update(dependency_extras)
            if dependency not in processed_extras or changed:
                pending.append(dependency)
    unreachable = sorted(set(packages) - set(requested_extras))
    if unreachable:
        raise PublishError(f"uv.lock contains unreachable packages: {', '.join(unreachable[:10])}")


def _validate_lock_structure(content: bytes) -> None:
    document = _parse_toml_document(content, "uv.lock")
    raw_packages = document.get("package")
    if document.get("version") != 1 or not isinstance(raw_packages, list) or not raw_packages:
        raise PublishError("uv.lock has an unsupported or incomplete schema")
    editable_projects = 0
    for index, raw_package in enumerate(raw_packages):
        package = _mapping(raw_package, f"uv.lock package {index}")
        name = _string(package.get("name"), f"uv.lock package {index} name")
        source = _mapping(package.get("source"), f"uv.lock package {name} source")
        if source == {"editable": "."}:
            if re.sub(r"[-_.]+", "-", name).lower() != "odyssey":
                raise PublishError("uv.lock contains an unexpected editable dependency")
            editable_projects += 1
        elif set(source) != {"registry"} or source.get("registry") not in TRUSTED_REGISTRIES:
            raise PublishError(f"uv.lock package {name} uses an untrusted URL or non-registry source")
    if editable_projects != 1:
        raise PublishError("uv.lock must contain exactly one trusted Odyssey editable project")
    _validate_lock_reachability(raw_packages)
    _validate_lock_urls(document)


def _validate_requirement_export(content: bytes, relative_path: str) -> None:
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as error:
        raise PublishError(f"{relative_path} is not valid UTF-8") from error
    if not text or not text.endswith("\n") or "\r" in text or "\x00" in text:
        raise PublishError(f"{relative_path} is empty or has noncanonical line endings")
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if (
            stripped.startswith(("-", "."))
            or "://" in stripped
            or " @ " in stripped
            or stripped.startswith(("file:", "git+"))
        ):
            raise PublishError(f"{relative_path} contains an include, option, path, or URL")


def _run_validation_command(
    command: list[str],
    *,
    cwd: Path,
    environment: Mapping[str, str],
    runner: Callable[..., subprocess.CompletedProcess[str]],
    description: str,
) -> subprocess.CompletedProcess[str]:
    try:
        completed = runner(
            command,
            cwd=cwd,
            check=False,
            capture_output=True,
            text=True,
            env=dict(environment),
            timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise PublishError(f"{description} could not run: {error}") from error
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip()
        raise PublishError(f"{description} failed{f': {detail}' if detail else ''}")
    return completed


def validate_canonical_dependencies(
    bundle: ArtifactBundle,
    *,
    candidate_pyproject: bytes,
    trusted_pyproject: bytes,
    trusted_lock: bytes,
    trusted_python_version: bytes,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
    uv_binary: str = "uv",
) -> None:
    """Independently prove candidate files by regenerating from trusted inputs."""
    _validate_candidate_pyproject(candidate_pyproject, trusted_pyproject)
    _validate_lock_structure(bundle.files["uv.lock"])
    _validate_lock_structure(trusted_lock)
    for relative_path in ("requirements.txt", "requirements-dev.txt"):
        _validate_requirement_export(bundle.files[relative_path], relative_path)
    try:
        python_version = trusted_python_version.decode("ascii")
    except UnicodeDecodeError as error:
        raise PublishError("trusted .python-version is not ASCII") from error
    if not re.fullmatch(r"3\.\d+\n", python_version):
        raise PublishError("trusted .python-version is malformed")

    sync_script = Path(__file__).resolve().parents[1] / "sync_requirements.py"
    _read_regular_file(
        sync_script,
        maximum_bytes=MAX_REPOSITORY_DATA_BYTES,
        description="trusted requirements synchronizer",
    )
    with tempfile.TemporaryDirectory(prefix="odyssey-dependency-validation-") as temporary_directory:
        validation_root = Path(temporary_directory)
        (validation_root / PROJECT_METADATA_PATH).write_bytes(candidate_pyproject)
        (validation_root / PYTHON_VERSION_PATH).write_bytes(trusted_python_version)
        (validation_root / "uv.lock").write_bytes(trusted_lock)
        for relative_path in ("requirements.txt", "requirements-dev.txt"):
            (validation_root / relative_path).write_bytes(bundle.files[relative_path])
        environment = {
            "HOME": temporary_directory,
            "LANG": "C.UTF-8",
            "PATH": os.environ.get("PATH", ""),
            "PYTHONUTF8": "1",
            "UV_CACHE_DIR": str(validation_root / ".uv-cache"),
            "UV_PYTHON": python_version.strip(),
        }
        version = _run_validation_command(
            [uv_binary, "--version"],
            cwd=validation_root,
            environment=environment,
            runner=runner,
            description="trusted uv version check",
        )
        version_fields = version.stdout.strip().split()
        if len(version_fields) < 2 or version_fields[:2] != ["uv", TRUSTED_UV_VERSION]:
            raise PublishError(f"trusted publisher requires uv {TRUSTED_UV_VERSION}")
        regeneration_command = [uv_binary, "lock", "--no-build", "--prerelease", "allow"]
        _run_validation_command(
            regeneration_command,
            cwd=validation_root,
            environment=environment,
            runner=runner,
            description="trusted uv lock regeneration",
        )
        if (validation_root / "uv.lock").read_bytes() != bundle.files["uv.lock"]:
            raise PublishError("uv.lock is not the canonical pinned-uv result from the trusted default lock")
        offline_environment = {**environment, "UV_OFFLINE": "1"}
        _run_validation_command(
            [uv_binary, "lock", "--check", "--offline", "--prerelease", "allow"],
            cwd=validation_root,
            environment=offline_environment,
            runner=runner,
            description="trusted uv lock check",
        )
        _run_validation_command(
            [
                sys.executable,
                str(sync_script),
                "--check",
                "--repo-root",
                str(validation_root),
            ],
            cwd=validation_root,
            environment=offline_environment,
            runner=runner,
            description="trusted canonical requirements export check",
        )


def validate_published_dependency_candidate(
    bundle: ArtifactBundle,
    *,
    trusted_default_oid: str,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> None:
    """Fetch immutable project inputs and apply the trusted canonical validator."""
    _validate_oid(trusted_default_oid, "trusted default-branch OID")
    validate_canonical_dependencies(
        bundle,
        candidate_pyproject=get_file_at_oid(
            bundle.repository,
            PROJECT_METADATA_PATH,
            bundle.head_sha,
            token=token,
            opener=opener,
        ),
        trusted_pyproject=get_file_at_oid(
            bundle.repository,
            PROJECT_METADATA_PATH,
            trusted_default_oid,
            token=token,
            opener=opener,
        ),
        trusted_lock=get_file_at_oid(
            bundle.repository,
            "uv.lock",
            trusted_default_oid,
            token=token,
            opener=opener,
        ),
        trusted_python_version=get_file_at_oid(
            bundle.repository,
            PYTHON_VERSION_PATH,
            trusted_default_oid,
            token=token,
            opener=opener,
        ),
    )


def post_graphql(
    payload: GraphQLPayload,
    token: str,
    *,
    opener: UrlOpener = urllib.request.urlopen,
) -> GraphQLPayload:
    """POST one standard-library request to GitHub's fixed GraphQL endpoint."""
    if not token:
        raise PublishError("GITHUB_TOKEN is missing")
    request = urllib.request.Request(
        GRAPHQL_URL,
        data=json.dumps(payload, separators=(",", ":")).encode(),
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "Odyssey-dependency-publisher",
        },
        method="POST",
    )
    response = _open_json(request, opener=opener, description="GitHub GraphQL request")
    if response is None:
        raise PublishError("GitHub GraphQL request unexpectedly returned no response")
    return response


def _open_json(
    request: urllib.request.Request,
    *,
    opener: UrlOpener,
    description: str,
    missing_ok: bool = False,
) -> GraphQLPayload | None:
    try:
        with opener(request, timeout=30) as response:
            status_code = int(response.status)
            body = response.read()
    except urllib.error.HTTPError as error:
        if missing_ok and error.code == 404:
            return None
        raise PublishError(f"{description} failed with HTTP {error.code}") from error
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise PublishError(f"{description} failed: {error}") from error
    if missing_ok and status_code == 404:
        return None
    if status_code != 200:
        raise PublishError(f"{description} failed with HTTP {status_code}")
    try:
        decoded = json.loads(body)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise PublishError(f"{description} returned malformed JSON") from error
    if not isinstance(decoded, dict):
        raise PublishError(f"{description} returned a non-object JSON value")
    return decoded


def _rest_get(
    url: str,
    *,
    token: str,
    opener: UrlOpener,
    description: str,
    missing_ok: bool = False,
) -> GraphQLPayload | None:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "Odyssey-dependency-publisher",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="GET",
    )
    return _open_json(request, opener=opener, description=description, missing_ok=missing_ok)


def _api_root(repository: str) -> str:
    return f"https://api.github.com/repos/{urllib.parse.quote(repository, safe='/')}"


def verify_live_source_run(
    context: RunContext,
    *,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> None:
    """Refetch and authenticate the exact workflow file and source run."""
    response = _rest_get(
        f"{_api_root(context.repository)}/actions/runs/{context.run_id}",
        token=token,
        opener=opener,
        description="source workflow run lookup",
    )
    if response is None:
        raise PublishError("source workflow run lookup unexpectedly returned no response")
    expected_fields = {
        "id": context.run_id,
        "run_attempt": context.run_attempt,
        "workflow_id": context.workflow_id,
        "name": GENERATOR_WORKFLOW,
        "path": GENERATOR_WORKFLOW_PATH,
        "event": "pull_request",
        "conclusion": "success",
        "head_branch": context.head_ref,
        "head_sha": context.head_sha,
    }
    for field, expected in expected_fields.items():
        if response.get(field) != expected:
            raise PublishError(f"source workflow run {field} does not match the trusted event")
    actor = _mapping(response.get("actor"), "source workflow run actor")
    if actor.get("login") != BOT_LOGIN:
        raise PublishError("source workflow run actor is not Dependabot")
    repository = _mapping(response.get("repository"), "source workflow run repository")
    head_repository = _mapping(response.get("head_repository"), "source workflow run head repository")
    if (
        repository.get("id") != context.repository_id
        or repository.get("full_name") != context.repository
        or head_repository.get("id") != context.head_repository_id
        or head_repository.get("full_name") != context.repository
    ):
        raise PublishError("source workflow run repository identity does not match the trusted event")

    workflow = _rest_get(
        f"{_api_root(context.repository)}/actions/workflows/{context.workflow_id}",
        token=token,
        opener=opener,
        description="source workflow identity lookup",
    )
    if workflow is None:
        raise PublishError("source workflow identity lookup unexpectedly returned no response")
    if (
        workflow.get("id") != context.workflow_id
        or workflow.get("name") != GENERATOR_WORKFLOW
        or workflow.get("path") != GENERATOR_WORKFLOW_PATH
        or workflow.get("state") != "active"
    ):
        raise PublishError("source workflow run does not belong to the exact active generator workflow")


def get_branch_head(
    repository: str,
    branch: str,
    *,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> str | None:
    """Return the exact branch OID, or None after deletion."""
    _validate_repository(repository)
    _validate_branch(branch)
    encoded_branch = urllib.parse.quote(branch, safe="")
    response = _rest_get(
        f"{_api_root(repository)}/git/ref/heads/{encoded_branch}",
        token=token,
        opener=opener,
        description="Dependabot branch lookup",
        missing_ok=True,
    )
    if response is None:
        return None
    target = _mapping(response.get("object"), "Dependabot branch object")
    oid = _string(target.get("sha"), "Dependabot branch object ID")
    _validate_oid(oid, "Dependabot branch object ID")
    return oid


def get_pull_request_head(
    context: RunContext,
    *,
    pr_number: int,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> str | None:
    """Verify the live open Dependabot PR and return its current head."""
    response = _rest_get(
        f"{_api_root(context.repository)}/pulls/{pr_number}",
        token=token,
        opener=opener,
        description="Dependabot pull request lookup",
        missing_ok=True,
    )
    if response is None or response.get("state") != "open":
        return None
    user = _mapping(response.get("user"), "pull request user")
    head = _mapping(response.get("head"), "pull request head")
    base = _mapping(response.get("base"), "pull request base")
    head_repository = _mapping(head.get("repo"), "pull request head repository")
    if user.get("login") != BOT_LOGIN:
        raise PublishError("live pull request author is not Dependabot")
    if head_repository.get("full_name") != context.repository:
        raise PublishError("live pull request head repository is not the target repository")
    if head.get("ref") != context.head_ref:
        raise PublishError("live pull request head branch contradicts workflow_run")
    if base.get("ref") != context.default_branch:
        raise PublishError("live pull request no longer targets the default branch")
    oid = _string(head.get("sha"), "live pull request head SHA")
    _validate_oid(oid, "live pull request head SHA")
    return oid


def get_file_at_oid(
    repository: str,
    relative_path: str,
    oid: str,
    *,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> bytes:
    """Fetch one allowlisted repository file as data at an immutable Git OID."""
    if relative_path not in REPOSITORY_DATA_PATHS:
        raise PublishError(f"unexpected repository data path: {relative_path}")
    _validate_oid(oid)
    encoded_path = urllib.parse.quote(relative_path, safe="/")
    query = urllib.parse.urlencode({"ref": oid})
    response = _rest_get(
        f"{_api_root(repository)}/contents/{encoded_path}?{query}",
        token=token,
        opener=opener,
        description=f"repository content lookup for {relative_path}",
    )
    if response is None:
        raise PublishError(f"repository content lookup unexpectedly omitted {relative_path}")
    if response.get("type") != "file" or response.get("encoding") != "base64":
        raise PublishError(f"repository content for {relative_path} is not an inline base64 file")
    encoded_content = _string(response.get("content"), f"repository content for {relative_path}")
    try:
        content = base64.b64decode(encoded_content.replace("\n", ""), validate=True)
    except (ValueError, binascii.Error) as error:
        raise PublishError(f"repository content for {relative_path} is malformed base64") from error
    if len(content) > MAX_REPOSITORY_DATA_BYTES:
        raise PublishError(f"repository content for {relative_path} exceeds the size limit")
    if response.get("size") != len(content):
        raise PublishError(f"repository content size contradicts decoded bytes for {relative_path}")
    return content


def compare_artifact_to_source(
    bundle: ArtifactBundle,
    *,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> tuple[str, ...]:
    """Return exact changed paths and reject a contradictory changed flag."""
    changed_paths = tuple(
        relative_path
        for relative_path in GENERATED_PATHS
        if bundle.files[relative_path]
        != get_file_at_oid(
            bundle.repository,
            relative_path,
            bundle.head_sha,
            token=token,
            opener=opener,
        )
    )
    if bundle.changed != bool(changed_paths):
        raise PublishError("artifact changed flag contradicts immutable source contents")
    return changed_paths


def _commit_headline(pr_number: int) -> str:
    return f"fix(uv): regenerate dependency files for Dependabot PR #{pr_number}"


def _commit_message(pr_number: int) -> str:
    return f"{_commit_headline(pr_number)}\n\n{DCO_BODY}"


def build_commit_payload(bundle: ArtifactBundle) -> GraphQLPayload:
    """Build a three-file, expected-parent-bound, DCO-signed mutation."""
    additions = [
        {
            "path": relative_path,
            "contents": base64.b64encode(bundle.files[relative_path]).decode("ascii"),
        }
        for relative_path in GENERATED_PATHS
    ]
    return {
        "query": CREATE_COMMIT_MUTATION,
        "variables": {
            "input": {
                "branch": {
                    "repositoryNameWithOwner": bundle.repository,
                    "branchName": bundle.head_ref,
                },
                "expectedHeadOid": bundle.head_sha,
                "message": {
                    "headline": _commit_headline(bundle.pr_number),
                    "body": DCO_BODY,
                },
                "fileChanges": {"additions": additions},
            }
        },
    }


def _validate_signature(signature_value: object) -> None:
    signature = _mapping(signature_value, "commit signature")
    if signature.get("isValid") is not True:
        raise PublishError("generated dependency commit signature is not valid")
    if signature.get("state") != "VALID":
        raise PublishError("generated dependency commit signature state is not VALID")
    if signature.get("wasSignedByGitHub") is not True:
        raise PublishError("generated dependency commit was not signed by GitHub")


def validate_create_response(response: Mapping[str, Any], *, branch: str) -> CommitResult:
    """Validate the mutation result before performing independent exact-child checks."""
    errors = response.get("errors")
    if errors:
        messages: list[str] = []
        if isinstance(errors, list):
            for error in errors:
                if isinstance(error, Mapping) and isinstance(error.get("message"), str):
                    messages.append(error["message"])
        raise PublishError(f"GitHub rejected generated dependency commit: {'; '.join(messages) or 'unknown error'}")
    data = _mapping(response.get("data"), "GraphQL data")
    mutation = _mapping(data.get("createCommitOnBranch"), "createCommitOnBranch result")
    commit = _mapping(mutation.get("commit"), "created commit")
    _validate_signature(commit.get("signature"))
    oid = _string(commit.get("oid"), "created commit OID")
    _validate_oid(oid, "created commit OID")
    url = _string(commit.get("url"), "created commit URL")
    expected_suffix = f"/commit/{oid}"
    if not url.startswith("https://github.com/") or not url.endswith(expected_suffix):
        raise PublishError("created commit URL is not a GitHub commit URL for the returned OID")
    ref = _mapping(mutation.get("ref"), "updated ref")
    if ref.get("name") not in {branch, f"refs/heads/{branch}"}:
        raise PublishError("createCommitOnBranch updated an unexpected ref")
    target = _mapping(ref.get("target"), "updated ref target")
    if target.get("oid") != oid:
        raise PublishError("createCommitOnBranch ref target contradicts the commit OID")
    return CommitResult(oid=oid, url=url)


def create_signed_commit(
    bundle: ArtifactBundle,
    *,
    token: str,
    sender: GraphQLSender = post_graphql,
) -> CommitResult:
    """Create a GitHub-signed commit only if the source OID is still current."""
    return validate_create_response(sender(build_commit_payload(bundle), token), branch=bundle.head_ref)


def verify_exact_child(
    *,
    bundle: ArtifactBundle,
    commit_oid: str,
    changed_paths: tuple[str, ...],
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
    sender: GraphQLSender = post_graphql,
) -> CommitResult:
    """Verify parent, diff, message, signature, and exact file contents."""
    _validate_oid(commit_oid, "candidate child OID")
    commit_response = _rest_get(
        f"{_api_root(bundle.repository)}/commits/{commit_oid}",
        token=token,
        opener=opener,
        description="candidate generated commit lookup",
    )
    if commit_response is None:
        raise PublishError("candidate generated commit lookup unexpectedly returned no response")
    if commit_response.get("sha") != commit_oid:
        raise ExactChildMismatch("candidate generated commit lookup returned the wrong OID")
    commit_data = _mapping(commit_response.get("commit"), "candidate commit data")
    if commit_data.get("message") != _commit_message(bundle.pr_number):
        raise ExactChildMismatch("candidate generated commit message or DCO body is not exact")
    parents = commit_response.get("parents")
    if (
        not isinstance(parents, list)
        or len(parents) != 1
        or not isinstance(parents[0], Mapping)
        or parents[0].get("sha") != bundle.head_sha
    ):
        raise ExactChildMismatch("candidate generated commit is not an exact child of the workflow head")
    raw_files = commit_response.get("files")
    if not isinstance(raw_files, list):
        raise ExactChildMismatch("candidate generated commit omitted its changed file list")
    commit_paths: list[str] = []
    for entry in raw_files:
        if not isinstance(entry, Mapping) or not isinstance(entry.get("filename"), str):
            raise ExactChildMismatch("candidate generated commit has a malformed changed file entry")
        commit_paths.append(entry["filename"])
    if sorted(commit_paths) != sorted(changed_paths):
        raise ExactChildMismatch("candidate generated commit changes files outside the exact artifact diff")

    owner, name = bundle.repository.split("/", 1)
    signature_response = sender(
        {
            "query": VERIFY_COMMIT_QUERY,
            "variables": {"owner": owner, "name": name, "oid": commit_oid},
        },
        token,
    )
    if signature_response.get("errors"):
        raise ExactChildMismatch("GitHub rejected exact-child signature verification")
    data = _mapping(signature_response.get("data"), "signature query data")
    repository = _mapping(data.get("repository"), "signature query repository")
    commit = _mapping(repository.get("object"), "signature query commit")
    if commit.get("oid") != commit_oid:
        raise ExactChildMismatch("signature query returned the wrong commit")
    try:
        _validate_signature(commit.get("signature"))
    except PublishError as error:
        raise ExactChildMismatch(str(error)) from error
    url = _string(commit.get("url"), "verified commit URL")

    for relative_path in GENERATED_PATHS:
        published = get_file_at_oid(
            bundle.repository,
            relative_path,
            commit_oid,
            token=token,
            opener=opener,
        )
        if published != bundle.files[relative_path]:
            raise ExactChildMismatch(f"candidate child content does not match artifact: {relative_path}")
    return CommitResult(oid=commit_oid, url=url)


def _workflow_runs(
    repository: str,
    workflow: str,
    branch: str,
    *,
    token: str,
    opener: UrlOpener,
) -> list[Mapping[str, Any]]:
    query = urllib.parse.urlencode(
        {
            "branch": branch,
            "event": "workflow_dispatch",
            "per_page": 100,
        }
    )
    encoded_workflow = urllib.parse.quote(workflow, safe="")
    response = _rest_get(
        f"{_api_root(repository)}/actions/workflows/{encoded_workflow}/runs?{query}",
        token=token,
        opener=opener,
        description=f"workflow run lookup for {workflow}",
    )
    if response is None:
        raise PublishError(f"workflow run lookup for {workflow} unexpectedly returned no response")
    raw_runs = response.get("workflow_runs")
    if not isinstance(raw_runs, list):
        raise PublishError(f"workflow run lookup for {workflow} returned malformed data")
    return [run for run in raw_runs if isinstance(run, Mapping)]


def _dispatch_workflow(
    repository: str,
    workflow: str,
    branch: str,
    *,
    token: str,
    opener: UrlOpener,
) -> None:
    encoded_workflow = urllib.parse.quote(workflow, safe="")
    request = urllib.request.Request(
        f"{_api_root(repository)}/actions/workflows/{encoded_workflow}/dispatches",
        data=json.dumps({"ref": branch}, separators=(",", ":")).encode(),
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "Odyssey-dependency-publisher",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with opener(request, timeout=30) as response:
            status_code = int(response.status)
            response.read()
    except urllib.error.HTTPError as error:
        raise PublishError(f"workflow dispatch for {workflow} failed with HTTP {error.code}") from error
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise PublishError(f"workflow dispatch for {workflow} failed: {error}") from error
    if status_code != 204:
        raise PublishError(f"workflow dispatch for {workflow} failed with HTTP {status_code}")


def authenticate_required_workflows(
    *,
    repository: str,
    commit_oid: str,
    trusted_default_oid: str,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
) -> None:
    """Require every dispatched workflow blob to equal the immutable trusted copy."""
    _validate_repository(repository)
    _validate_oid(commit_oid, "published GraphQL commit OID")
    _validate_oid(trusted_default_oid, "trusted default-branch OID")
    for workflow_path in REQUIRED_WORKFLOW_PATHS:
        trusted_content = get_file_at_oid(
            repository,
            workflow_path,
            trusted_default_oid,
            token=token,
            opener=opener,
        )
        candidate_content = get_file_at_oid(
            repository,
            workflow_path,
            commit_oid,
            token=token,
            opener=opener,
        )
        if candidate_content != trusted_content:
            raise PublishError(
                f"refusing to dispatch modified required workflow {workflow_path}; "
                "Dependabot branch must be updated from the trusted default branch"
            )


def dispatch_required_workflows(
    *,
    repository: str,
    branch: str,
    commit_oid: str,
    trusted_default_oid: str,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
    sleeper: Callable[[float], None] = time.sleep,
    poll_attempts: int = 10,
) -> int:
    """Idempotently dispatch the literal allowlist and bind every run to the OID."""
    _validate_repository(repository)
    _validate_branch(branch)
    _validate_oid(commit_oid, "published GraphQL commit OID")
    _validate_oid(trusted_default_oid, "trusted default-branch OID")
    if poll_attempts <= 0:
        raise PublishError("workflow dispatch poll attempts must be positive")
    authenticate_required_workflows(
        repository=repository,
        commit_oid=commit_oid,
        trusted_default_oid=trusted_default_oid,
        token=token,
        opener=opener,
    )
    dispatched = 0
    for workflow in REQUIRED_WORKFLOWS:
        if get_branch_head(repository, branch, token=token, opener=opener) != commit_oid:
            raise StaleBranch(f"branch moved before dispatching {workflow}")
        runs = _workflow_runs(repository, workflow, branch, token=token, opener=opener)
        if any(run.get("head_sha") == commit_oid for run in runs):
            print(f"Already dispatched {workflow} on {commit_oid}; resuming")
            continue

        _dispatch_workflow(repository, workflow, branch, token=token, opener=opener)
        dispatched += 1
        for attempt in range(poll_attempts):
            runs = _workflow_runs(repository, workflow, branch, token=token, opener=opener)
            matching_runs = [run for run in runs if run.get("head_sha") == commit_oid]
            if matching_runs:
                run_url = next(
                    (str(run["html_url"]) for run in matching_runs if isinstance(run.get("html_url"), str)),
                    "run created",
                )
                print(f"Dispatched {workflow} on {commit_oid}: {run_url}")
                break
            if attempt + 1 < poll_attempts:
                sleeper(1.0)
        else:
            raise PublishError(f"workflow dispatch for {workflow} did not bind to GraphQL OID {commit_oid}")
    if get_branch_head(repository, branch, token=token, opener=opener) != commit_oid:
        raise StaleBranch("branch moved during required workflow dispatch")
    return dispatched


def wait_for_published_head(
    *,
    context: RunContext,
    pr_number: int,
    expected_oid: str,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
    sleeper: Callable[[float], None] = time.sleep,
    poll_attempts: int = 10,
) -> bool:
    """Wait for branch and PR APIs to expose the verified child.

    A genuinely newer OID is stale and returns False. Temporary visibility of
    the original parent is retried so a successful mutation cannot silently
    finish without dispatching its required checks.
    """
    if poll_attempts <= 0:
        raise PublishError("published-head poll attempts must be positive")
    for attempt in range(poll_attempts):
        current_pr_head = get_pull_request_head(
            context,
            pr_number=pr_number,
            token=token,
            opener=opener,
        )
        current_branch_head = get_branch_head(
            context.repository,
            context.head_ref,
            token=token,
            opener=opener,
        )
        if current_pr_head == expected_oid and current_branch_head == expected_oid:
            return True
        observed = {current_pr_head, current_branch_head}
        if None in observed or not observed.issubset({context.head_sha, expected_oid}):
            return False
        if attempt + 1 < poll_attempts:
            sleeper(1.0)
    raise PublishError(f"live pull request did not converge on published commit {expected_oid}")


def publish_dependencies(
    *,
    context: RunContext,
    bundle: ArtifactBundle,
    trusted_default_oid: str,
    token: str,
    opener: UrlOpener = urllib.request.urlopen,
    sender: GraphQLSender = post_graphql,
    sleeper: Callable[[float], None] = time.sleep,
) -> PublishResult:
    """Publish once, resume safely after partial completion, or no-op if stale."""
    _validate_oid(trusted_default_oid, "trusted default-branch OID")
    live_pr_head = get_pull_request_head(
        context,
        pr_number=bundle.pr_number,
        token=token,
        opener=opener,
    )
    live_branch_head = get_branch_head(context.repository, context.head_ref, token=token, opener=opener)
    if live_pr_head is None or live_branch_head is None:
        return PublishResult("stale", None, 0)

    validate_published_dependency_candidate(
        bundle,
        trusted_default_oid=trusted_default_oid,
        token=token,
        opener=opener,
    )
    changed_paths = compare_artifact_to_source(bundle, token=token, opener=opener)
    if not changed_paths:
        if live_pr_head != bundle.head_sha or live_branch_head != bundle.head_sha:
            return PublishResult("stale", None, 0)
        return PublishResult("unchanged", bundle.head_sha, 0)

    verified: CommitResult | None = None
    if live_pr_head != live_branch_head:
        observed_heads = {live_pr_head, live_branch_head}
        child_candidates = observed_heads - {bundle.head_sha}
        if bundle.head_sha not in observed_heads or len(child_candidates) != 1:
            return PublishResult("stale", None, 0)
        candidate_oid = next(iter(child_candidates))
        try:
            verified = verify_exact_child(
                bundle=bundle,
                commit_oid=candidate_oid,
                changed_paths=changed_paths,
                token=token,
                opener=opener,
                sender=sender,
            )
        except ExactChildMismatch:
            return PublishResult("stale", None, 0)

        if not wait_for_published_head(
            context=context,
            pr_number=bundle.pr_number,
            expected_oid=verified.oid,
            token=token,
            opener=opener,
            sleeper=sleeper,
        ):
            return PublishResult("stale", None, 0)
        live_branch_head = verified.oid

    if live_branch_head == bundle.head_sha:
        try:
            created = create_signed_commit(bundle, token=token, sender=sender)
        except PublishError:
            raced_head = get_branch_head(
                context.repository,
                context.head_ref,
                token=token,
                opener=opener,
            )
            if raced_head is None or raced_head == bundle.head_sha:
                raise
            live_branch_head = raced_head
        else:
            live_branch_head = created.oid

    if live_branch_head == bundle.head_sha:
        raise PublishError("GitHub did not advance the Dependabot branch")
    if verified is None:
        try:
            verified = verify_exact_child(
                bundle=bundle,
                commit_oid=live_branch_head,
                changed_paths=changed_paths,
                token=token,
                opener=opener,
                sender=sender,
            )
        except ExactChildMismatch:
            return PublishResult("stale", None, 0)

        if not wait_for_published_head(
            context=context,
            pr_number=bundle.pr_number,
            expected_oid=verified.oid,
            token=token,
            opener=opener,
            sleeper=sleeper,
        ):
            return PublishResult("stale", None, 0)
    dispatched = dispatch_required_workflows(
        repository=context.repository,
        branch=context.head_ref,
        commit_oid=verified.oid,
        trusted_default_oid=trusted_default_oid,
        token=token,
        opener=opener,
        sleeper=sleeper,
    )
    return PublishResult("published", verified.oid, dispatched)


def _required_environment(name: str) -> str:
    value = os.environ.get(name, "")
    if not value:
        raise PublishError(f"required environment variable is missing: {name}")
    return value


def _positive_environment_integer(name: str) -> int:
    try:
        value = int(_required_environment(name))
    except ValueError as error:
        raise PublishError(f"{name} must be an integer") from error
    return _integer(value, name)


def _package_from_cli(args: argparse.Namespace) -> None:
    changed_value = _required_environment("DEPS_CHANGED")
    if changed_value not in {"true", "false"}:
        raise PublishError("DEPS_CHANGED must be 'true' or 'false'")
    package_artifact(
        repo_root=args.repo_root.resolve(),
        artifact_root=args.artifact_root.resolve(),
        repository=_required_environment("TARGET_REPOSITORY"),
        pr_number=_positive_environment_integer("PR_NUMBER"),
        head_repository=_required_environment("HEAD_REPOSITORY"),
        head_ref=_required_environment("HEAD_REF"),
        head_sha=_required_environment("HEAD_SHA"),
        run_id=_positive_environment_integer("WORKFLOW_RUN_ID"),
        run_attempt=_positive_environment_integer("WORKFLOW_RUN_ATTEMPT"),
        producer_status=_required_environment("PRODUCER_STATUS"),
        changed=changed_value == "true",
        snapshot_path=args.snapshot_path.resolve(),
    )


def _snapshot_from_cli(args: argparse.Namespace) -> None:
    write_dependency_snapshot(
        repo_root=args.repo_root.resolve(),
        snapshot_path=args.snapshot_path.resolve(),
    )


def _publish_from_cli(args: argparse.Namespace) -> PublishResult:
    repository = _required_environment("TARGET_REPOSITORY")
    token = _required_environment("GITHUB_TOKEN")
    trusted_default_oid = _required_environment("TRUSTED_DEFAULT_SHA")
    _validate_oid(trusted_default_oid, "TRUSTED_DEFAULT_SHA")
    context = load_run_context(args.event_path.resolve(), target_repository=repository)
    verify_live_source_run(context, token=token)
    bundle = download_validated_artifact(context, token=token)
    return publish_dependencies(
        context=context,
        bundle=bundle,
        trusted_default_oid=trusted_default_oid,
        token=token,
    )


def main(argv: Sequence[str] | None = None) -> int:
    """Run the producer packager or trusted default-branch publisher."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    package_parser = subparsers.add_parser("package")
    package_parser.add_argument("--repo-root", type=Path, required=True)
    package_parser.add_argument("--artifact-root", type=Path, required=True)
    package_parser.add_argument("--snapshot-path", type=Path, required=True)
    snapshot_parser = subparsers.add_parser("snapshot")
    snapshot_parser.add_argument("--repo-root", type=Path, required=True)
    snapshot_parser.add_argument("--snapshot-path", type=Path, required=True)
    publish_parser = subparsers.add_parser("publish")
    publish_parser.add_argument("--event-path", type=Path, required=True)
    args = parser.parse_args(argv)

    try:
        if args.command == "package":
            _package_from_cli(args)
            print(f"Packaged exact {ARTIFACT_NAME} artifact")
        elif args.command == "snapshot":
            _snapshot_from_cli(args)
            print("Snapshotted exact verified dependency files")
        else:
            result = _publish_from_cli(args)
            if result.status == "stale":
                print("Dependabot branch is stale, moved, closed, or non-exact; no write performed")
            elif result.status == "unchanged":
                print("Generated dependency files are unchanged; no write or dispatch needed")
            else:
                print(
                    f"Published verified GitHub-signed commit {result.oid}; "
                    f"dispatched {result.dispatched} missing required workflows"
                )
    except StaleBranch as error:
        print(f"Dependabot branch became stale; stopped safely: {error}")
        return 0
    except (PublishError, OSError, ValueError) as error:
        print(f"ERROR: dependency artifact publication failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
