# test_{{module_name}}.mojo
"""
Tests for {{module_path}}.

Auto-generated by scripts/generators/generate_tests.py

NOTE: This is a code generation template. Lines marked with # TEMPLATE: are
intentional placeholders that must be filled in during code generation.
Do NOT remove these placeholders - they are required for code generation to work.
"""

from testing import assert_equal, assert_true, assert_false
from {{module_path}} import *
from shared.core import ExTensor


fn create_test_data() -> ExTensor:
    """Create test data with reproducible FP-representable values."""
    return ExTensor.from_list([0.0, 0.5, 1.0, 1.5, -0.5, -1.0])


fn test_initialization():
    """Test basic initialization."""
    # TEMPLATE: Test object creation (filled in during code generation)
    pass


fn test_basic_operation():
    """Test basic operations."""
    # TEMPLATE: Test core functionality (filled in during code generation)
    pass


fn test_empty_input():
    """Test behavior with empty inputs."""
    # TEMPLATE: Test empty case handling (filled in during code generation)
    pass


fn test_single_element():
    """Test behavior with single element."""
    # TEMPLATE: Test single element case (filled in during code generation)
    pass


fn test_large_input():
    """Test behavior with large inputs."""
    # TEMPLATE: Test scalability (filled in during code generation)
    pass


fn test_invalid_input():
    """Test error handling for invalid inputs."""
    # TEMPLATE: Test error cases (filled in during code generation)
    pass


fn test_integration():
    """Test integration with other components."""
    # TEMPLATE: Test component interactions (filled in during code generation)
    pass


fn main():
    """Run all tests."""
    print("Running tests for {{module_path}}")
    print("=" * 60)

    test_initialization()
    print("  test_initialization ... PASSED")

    test_basic_operation()
    print("  test_basic_operation ... PASSED")

    test_empty_input()
    print("  test_empty_input ... PASSED")

    test_single_element()
    print("  test_single_element ... PASSED")

    test_large_input()
    print("  test_large_input ... PASSED")

    test_invalid_input()
    print("  test_invalid_input ... PASSED")

    test_integration()
    print("  test_integration ... PASSED")

    print()
    print("All tests passed!")
