name: Set Up Pixi Environment
description: Install Pixi and restore the cached environment.

inputs:
  pixi-version:
    description: Pixi version to install
    required: false
    default: latest
  cache:
    description: Whether to enable Pixi built-in caching
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: ${{ inputs.pixi-version }}
        cache: ${{ inputs.cache }}
